# docker-compose.yml
version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: daitssu_db
    hostname: daitssu_mysql
    # 서비스 배포 및 실행 옵션
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: blog
      MYSQL_USER: daitssu
      MYSQL_PASSWORD: daitssu12
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - daitssu_mysql_volume:/var/lib/mysql
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql

# 도커 볼륨
volumes:
  daitssu_mysql_volume: